# Generated by Django 5.2.4 on 2025-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0002_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sentiment_scores',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='sentiment_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
