# Generated by Django 5.2.4 on 2025-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0003_posts_sentiment_scores_posts_sentiment_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='sentiment_scores',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sentiment_summary',
        ),
        migrations.AddField(
            model_name='posts',
            name='dt_prediction',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='lr_prediction',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='lstm_prediction',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='rf_prediction',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='sentiment_overall',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='svm_prediction',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
